# Generated by Django 4.2 on 2025-04-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("males", models.PositiveIntegerField(default=0)),
                ("femelles", models.PositiveIntegerField(default=0)),
                ("reproducteurs", models.PositiveIntegerField(default=0)),
                ("a_vendre", models.PositiveIntegerField(default=0)),
                ("nourriture_kg", models.FloatField(default=0)),
                ("cages", models.PositiveIntegerField(default=1)),
                (
                    "argent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("mois_ecoules", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
