# Generated by Django 4.2 on 2025-04-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elevage_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elevage",
            old_name="nom",
            new_name="farm_nom",
        ),
    ]
