# Generated by Django 4.2 on 2025-04-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elevage_app", "0002_rename_nom_elevage_farm_nom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Individu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Femelle")], max_length=1
                    ),
                ),
                ("age_mois", models.PositiveIntegerField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("P", "Present"),
                            ("V", "Vendu"),
                            ("M", "Mort"),
                            ("G", "Gravide"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "elevage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individus",
                        to="elevage_app.elevage",
                    ),
                ),
            ],
        ),
    ]
