# Generated by Django 4.2 on 2025-04-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevage_app", "0003_individu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Regle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix_nourriture",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("prix_cage", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "prix_vente_lapin",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("consommation_1mois", models.FloatField(max_length=20)),
                ("consommation_2mois", models.FloatField(max_length=20)),
                ("consommation_3mois", models.FloatField(max_length=20)),
                (
                    "portee_max",
                    models.PositiveIntegerField(
                        default=4, verbose_name="Maximam de nombre de chaque femelle"
                    ),
                ),
                (
                    "cage_max",
                    models.PositiveIntegerField(
                        default=6, verbose_name="nombre adoptee"
                    ),
                ),
                (
                    "cage_surcharge",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Maximam de lapins dans chaque cage"
                    ),
                ),
                (
                    "age_min_gravidite_mois",
                    models.PositiveIntegerField(default=6, verbose_name="Minimum age"),
                ),
                (
                    "age_max_gravidite_mois",
                    models.PositiveIntegerField(default=48, verbose_name="maximam age"),
                ),
                (
                    "duree_gestation_mois",
                    models.PositiveBigIntegerField(
                        default=1, verbose_name="duree_gestion"
                    ),
                ),
            ],
        ),
    ]
