# Generated by Django 4.2 on 2025-04-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevage_app", "0004_regle"),
    ]

    operations = [
        migrations.AddField(
            model_name="individu",
            name="enceinte",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="individu",
            name="mois_gestation",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="regle",
            name="age_min_gravidite_mois",
            field=models.PositiveIntegerField(default=3, verbose_name="Minimum age"),
        ),
    ]
