# Generated by Django 4.2 on 2025-04-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevage_app", "0005_individu_enceinte_individu_mois_gestation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regle",
            options={"verbose_name": "Règle", "verbose_name_plural": "Règles"},
        ),
        migrations.AlterField(
            model_name="elevage",
            name="argent",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name="elevage",
            name="farm_nom",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
